[package]
name = "echor"
version = "0.1.0"
description = "Display a line of text"
edition = "2021"

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2.0.8"
